
-- Create indexes for kode_vendor field
CREATE INDEX idx_ref_adm_bu_kode_vendor ON ref_adm_bu (kode_vendor);
CREATE INDEX idx_ref_administrasi_pero_kode_vendor ON ref_administrasi_pero (kode_vendor);
CREATE INDEX idx_ref_data_pajak_bu_kode_vendor ON ref_data_pajak_bu (kode_vendor);
CREATE INDEX idx_ref_datadiri_kode_vendor ON ref_datadiri (kode_vendor);
CREATE INDEX idx_ref_direksi_bu_kode_vendor ON ref_direksi_bu (kode_vendor);
CREATE INDEX idx_ref_direksi_bu_custom_kode_vendor ON ref_direksi_bu_custom (kode_vendor);
CREATE INDEX idx_ref_fasilitas_bu_kode_vendor ON ref_fasilitas_bu (kode_vendor);
CREATE INDEX idx_ref_fasilitas_bu_custom_kode_vendor ON ref_fasilitas_bu_custom (kode_vendor);
CREATE INDEX idx_ref_history_adm_bu_kode_vendor ON ref_history_adm_bu (kode_vendor);
CREATE INDEX idx_ref_history_administrasi_pero_kode_vendor ON ref_history_administrasi_pero (kode_vendor);
CREATE INDEX idx_ref_history_data_pajak_bu_kode_vendor ON ref_history_data_pajak_bu (kode_vendor);
CREATE INDEX idx_ref_history_datadiri_umum_kode_vendor ON ref_history_datadiri_umum (kode_vendor);
CREATE INDEX idx_ref_history_direksi_bu_kode_vendor ON ref_history_direksi_bu (kode_vendor);
CREATE INDEX idx_ref_history_fasilitas_bu_kode_vendor ON ref_history_fasilitas_bu (kode_vendor);
CREATE INDEX idx_ref_history_izin_usaha_bu_kode_vendor ON ref_history_izin_usaha_bu (kode_vendor);
CREATE INDEX idx_ref_history_kantor_bu_kode_vendor ON ref_history_kantor_bu (kode_vendor);
CREATE INDEX idx_ref_history_keuangan_bu_kode_vendor ON ref_history_keuangan_bu (kode_vendor);
CREATE INDEX idx_ref_history_keuangan_pero_kode_vendor ON ref_history_keuangan_pero (kode_vendor);
CREATE INDEX idx_ref_history_komisaris_bu_kode_vendor ON ref_history_komisaris_bu (kode_vendor);
CREATE INDEX idx_ref_history_lan_hukum_bu_kode_vendor ON ref_history_lan_hukum_bu (kode_vendor);
CREATE INDEX idx_ref_history_pengalaman_bu_kode_vendor ON ref_history_pengalaman_bu (kode_vendor);
CREATE INDEX idx_ref_history_pengalaman_pero_kode_vendor ON ref_history_pengalaman_pero (kode_vendor);
CREATE INDEX idx_ref_history_pengurus_bu_kode_vendor ON ref_history_pengurus_bu (kode_vendor);
CREATE INDEX idx_ref_history_personalia_pero_kode_vendor ON ref_history_personalia_pero (kode_vendor);
CREATE INDEX idx_ref_history_saham_bu_kode_vendor ON ref_history_saham_bu (kode_vendor);
CREATE INDEX idx_ref_history_sertif_pero_kode_vendor ON ref_history_sertif_pero (kode_vendor);
CREATE INDEX idx_ref_history_sertifikat_usaha_bu_kode_vendor ON ref_history_sertifikat_usaha_bu (kode_vendor);
CREATE INDEX idx_ref_history_tenaga_ahli_bu_kode_vendor ON ref_history_tenaga_ahli_bu (kode_vendor);
CREATE INDEX idx_ref_history_tenaga_pendukung_bu_kode_vendor ON ref_history_tenaga_pendukung_bu (kode_vendor);
CREATE INDEX idx_ref_izin_usaha_bu_kode_vendor ON ref_izin_usaha_bu (kode_vendor);
CREATE INDEX idx_ref_izin_usaha_bu_custom_kode_vendor ON ref_izin_usaha_bu_custom (kode_vendor);
CREATE INDEX idx_ref_kantor_bu_kode_vendor ON ref_kantor_bu (kode_vendor);
CREATE INDEX idx_ref_kantor_bu_custom_kode_vendor ON ref_kantor_bu_custom (kode_vendor);
CREATE INDEX idx_ref_keuangan_bu_kode_vendor ON ref_keuangan_bu (kode_vendor);
CREATE INDEX idx_ref_keuangan_pero_kode_vendor ON ref_keuangan_pero (kode_vendor);
CREATE INDEX idx_ref_komisaris_bu_kode_vendor ON ref_komisaris_bu (kode_vendor);
CREATE INDEX idx_ref_lan_hukum_bu_kode_vendor ON ref_lan_hukum_bu (kode_vendor);
CREATE INDEX idx_ref_pakta_integritas_kode_vendor ON ref_pakta_integritas (kode_vendor);
CREATE INDEX idx_ref_penanggung_jwb_kode_vendor ON ref_penanggung_jwb (kode_vendor);
CREATE INDEX idx_ref_pengalaman_bu_kode_vendor ON ref_pengalaman_bu (kode_vendor);
CREATE INDEX idx_ref_pengalaman_bu_custom_kode_vendor ON ref_pengalaman_bu_custom (kode_vendor);
CREATE INDEX idx_ref_pengalaman_pero_kode_vendor ON ref_pengalaman_pero (kode_vendor);
CREATE INDEX idx_ref_pengurus_bu_kode_vendor ON ref_pengurus_bu (kode_vendor);
CREATE INDEX idx_ref_personalia_pero_kode_vendor ON ref_personalia_pero (kode_vendor);
CREATE INDEX idx_ref_saham_bu_kode_vendor ON ref_saham_bu (kode_vendor);
CREATE INDEX idx_ref_saham_bu_custom_kode_vendor ON ref_saham_bu_custom (kode_vendor);
CREATE INDEX idx_ref_sertif_pero_kode_vendor ON ref_sertif_pero (kode_vendor);
CREATE INDEX idx_ref_sertifikat_usaha_bu_kode_vendor ON ref_sertifikat_usaha_bu (kode_vendor);
CREATE INDEX idx_ref_sertifikat_usaha_bu_custom_kode_vendor ON ref_sertifikat_usaha_bu_custom (kode_vendor);
CREATE INDEX idx_ref_tenaga_ahli_bu_kode_vendor ON ref_tenaga_ahli_bu (kode_vendor);
CREATE INDEX idx_ref_tenaga_ahli_bu_custom_kode_vendor ON ref_tenaga_ahli_bu_custom (kode_vendor);
CREATE INDEX idx_ref_tenaga_pendukung_bu_kode_vendor ON ref_tenaga_pendukung_bu (kode_vendor);
CREATE INDEX idx_ref_tenaga_pendukung_bu_custom_kode_vendor ON ref_tenaga_pendukung_bu_custom (kode_vendor);
CREATE INDEX idx_ref_umum_kode_vendor ON ref_umum (kode_vendor);
CREATE INDEX idx_ref_v_keluar_dpt_kode_vendor ON ref_v_keluar_dpt (kode_vendor);
CREATE INDEX idx_ref_vendor_penandatangan_kode_vendor ON ref_vendor_penandatangan (kode_vendor);
CREATE INDEX idx_ref_vendor_reg_history_kode_vendor ON ref_vendor_reg_history (kode_vendor);
CREATE INDEX idx_ref_vendor_register_kode_vendor ON ref_vendor_register (kode_vendor);
CREATE INDEX idx_trx_custom_item_kode_vendor ON trx_custom_item (kode_vendor);
CREATE INDEX idx_trx_konfirmasi_data_sesuai_kode_vendor ON trx_konfirmasi_data_sesuai (kode_vendor);
CREATE INDEX idx_trx_undangan_penjr_kode_vendor ON trx_undangan_penjr (kode_vendor);
CREATE INDEX idx_trx_verif_luar_dpt_kode_vendor ON trx_verif_luar_dpt (kode_vendor);



CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_vendor_register_kode_vendor ON ref_vendor_register (kode_vendor);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_umum_kode_vendor ON ref_umum (kode_vendor);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_adm_bu_kode_vendor ON ref_adm_bu (kode_vendor);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_lan_hukum_bu_kode_vendor ON ref_lan_hukum_bu (kode_vendor);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_komisaris_bu_kode_vendor ON ref_komisaris_bu (kode_vendor);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ref_direksi_bu_kode_vendor ON ref_direksi_bu (kode_vendor);

