
Enum status_persetujuan {
  belum_diproses
  proses
  terima
  tolak
}

Enum metode_penjaringan {
  pengumuman
  undangan
}

/*
Enum status_evaluasi {
  belum_diproses
  proses_verifikasi
  perbaikan_data
  terevaluasi
}
*/

Enum jenis_item {
  "default"
  custom
}

Enum status_pengajuan_kat {
  draft
  proses_di_kasubdit
  proses_di_verifikator
  selesai
}

Enum status_pengajuan_pjr {
  draft
  proses_di_kasubdit
  proses_di_verifikator
  selesai
}

/*
Enum sertif_pengalaman {
  sertifikasi
  pengalaman
}
*/

/*
Enum jenis_personalia {
  tenaga_ahli
  tenaga_pendukung
}
*/

Enum status_vendor {
  aktif
  dibekukan
  dikeluarkan
}

Enum status_proses_pjr {
  belum_waktu_verifikasi
  proses
  proses_verifikasi
  proses_evaluasi
  selesai
}

Enum status_proses_dpt {
  belum_diumumkan
  diproses_ke_kasubdit
  selesai
}

Enum status_pembuatan_s_tugas {
  belum_diproses
  proses_ke_direktur
  selesai
}

Enum jenis_izin_usaha {
  nib
  sbu
  lainnya
}

Enum kondisi_barang {
  baik
  sedang
  kurang_baik
}


Enum status_verifikasi {
  belum_diproses
  proses_verifikasi
  perbaikan_data
  proses_evaluasi
  diterima
  ditolak
}

Enum status_dpt {
  belum_ditetapkan
  belum_penetapan
  terpilih
  tidak_terpilih
}

Table helper_kategori_kw {
  id serial [pk]
  keyword varchar
  kode_kategori int4
  kode_jenis_pengadaan int4

  note: "table sementara untuk bantu migrasi"
}

Table helper_bank_kw {
  id serial [pk]
  keyword varchar(255)
  sandi_bank varchar(4)
}

Table helper_pengusul_pjr {
  id serial [pk]
  nama_penjaringan varchar
  kode_jabatan_ppk int4

  note: "table sementara untuk bantu migrasi"
}

Table helper_domisili {
  kode_domisili int4 [pk]
  nama_domisili varchar
  kode_kab_kota varchar(5)
}

Table helper_user {
  id serial [pk]
  vms_user_id int4
  vms_user_name varchar(255)
  db_penyedia varchar(255)
  nama_penyedia varchar(255) [note: "ambil dari vmsdb.tbl_profile_penyedia.nama atau dari promise_sibela.tbl_profile_penyedia.nama"]
  jenis_penyedia varchar(255) [note: "perusahaan / perorangan"]
  kode_vendor int4
}

Table ref_bank {
  kode_bank serial [pk]
  sandi_bank varchar(4)
  nama_bank varchar(50)
}

Table ref_kbli {
  kode_kbli seria// l [pk]
  kategori varchar(2)
  gol_pokok int2
  gol int4
  sub_gol int4
  kelompok int4
  judul varchar
}


Table ref_kat_persyaratan {
  kode_kat_persyaratan serial [pk]
  kategori varchar(50)
}

Table ref_subkat_persyaratan {
  kode_subkat serial [pk]
  kode_kat_persyaratan int4
  sub_kategori varchar(100)
}

Table ref_kat_item_tanya {
  kode_kat_item_tanya serial [pk]
  kode_jenis_vendor int2
  kode_subkat int4
  kat_item_tanya varchar(200)
  nama_custom_field varchar(50)
}

Enum jenis_item_tanya {
  "default"
  custom
}

Table ref_item_tanya {
  kode_item serial [pk]
  kode_kat_item_tanya int4
  urutan int2
  nama_item varchar(100)
  nama_field varchar(50)
  tipe_input varchar(20)
  jenis_item jenis_item_tanya [note: "default, custom"]
  // nama_tabel varchar(50)
  nama_custom_field varchar(50)
  kode_penjaringan int4
  is_aktif bool
}

Table trx_ketentuan_umum_khusus {
  kode_kuk serial [pk]
  kode_penjaringan int4
  kode_subkat int4
  ket_umum varchar
  ket_khusus varchar
}

Table ref_item_tanya_tpl {
  kode_tpl serial [pk]
  kode_kat_item_tanya int4
  nama_item varchar(100)
  nama_field varchar(50)
  tipe_input varchar(20)

  note: "Master Custom Item"
}

Table ref_kategori {
  kode_kategori serial [pk]
  nama_kategori varchar

  note: 'Daftar kategori yang bisa digunakan PPK bila ada pengajuan'
}

Table ref_jenis_pengadaan {
  kode_jenis_pengadaan int2 [pk]
  jenis_pengadaan varchar

  note: "Barang, Jasa Konsultansi, Konstruksi, Jasa Lainnya"
}

/*
Table trx_kat_j_vendor {
  kode_kat_j_vendor serial [pk]
  kode_trx_kategori int4

  note: 'Untuk Input "Jenis Pelaku Usaha", Tiap trx_kategori bisa memilih jenis_vendor perorangan atau badan usaha atau dua2nya'
}
*/


Table trx_kategori {
  kode_trx_kategori serial [pk]
  kode_kategori int4 [ref: - ref_kategori.kode_kategori]
  status_persetujuan status_persetujuan [note: "Flag pengajuan paket diterima atau tidak (belum_diproses, proses, terima, tolak)"]
  keterangan_diterima text
  alasan_ditolak text
  kode_unit_pbj varchar(20) [note:'Unit yang mengajukan kategori, ambil dari ???']
  ucr varchar(80) [note: 'Email User yang membuat paket']
  uch varchar(80)
  udch timestamptz
  udcr timestamptz

  note: 'Paket pengadaan disebut dengan istilah "Kategori"'
}

Table ref_status_pengajuan_penjr {
  kode_status_pengajuan int [pk]
  status_umum varchar(30)
  status_di_ppk varchar(30)
}


Table trx_penjaringan {
  kode_penjaringan serial [pk, increment]
  kode_trx_kategori int4
  nama_penjaringan varchar(150)
  keperluan varchar(150)
  kode_jenis_pengadaan int2
  kode_jenis_vendor int2
  metode metode_penjaringan [note: "pengumuman, undangan"]
  kode_kualifikasi_usaha int2
  file_persyaratan text [note: "File PDF Persyaratan"]
  kode_status_pengajuan int4
  status_persetujuan status_persetujuan [note: "Flag pengajuan paket diterima atau tidak (belum_diproses, proses, terima, tolak)"]
  user_persetujuan varchar(80) [note: "Email user yang menerima atau menolak pengajuan penjaringan"]
  alasan_ditolak text
  status_pengajuan_pjr status_pengajuan_pjr [note: "draft, proses_di_kasubdit, proses_di_verifikator, selesai"]
  status_proses_pjr status_proses_pjr [note: "belum_waktu_verifikasi, proses, proses_verifikasi, proses_evaluasi, selesai"]
  status_pengumuman_dpt status_proses_dpt [note: "belum_diumumkan, diproses_ke_kasubdit, selesai"]
  tgl_daftar_awal timestamptz
  tgl_daftar_akhir timestamptz
  tgl_verifikasi_awal timestamptz
  tgl_verifikasi_akhir timestamptz
  tgl_evaluasi_awal timestamptz
  tgl_evaluasi_akhir timestamptz
  tgl_pengumuman timestamptz
  status_s_tugas status_pembuatan_s_tugas [note: "belum_diproses, proses_ke_direktur, selesai"]
  file_s_tugas varchar(255)
  keypass_s_tugas varchar(255)
  file_s_tugas_after_tte varchar(255)
  kode_trx_penandatangan int4
  nomor_surat varchar(100)
  file_pengumuman varchar(255)
  nama_pembuat_penjaringan varchar(100) [note: "Nama user yang mengusulkan penjaringan"]
  kode_unit_pbj varchar(20)
  ucr varchar(80) [note: "Email User yang mengusulkan penjaringan"]
  udcr timestamptz
  udch timestamptz
}



/*
Table ref_kualifikasi_penjr {
  kode_kualifikasi_penjr int2 [pk]
  kualifikasi_penjr varchar(10)

  note: "Kecil, Menengah, Besar"
}
*/

Table trx_verifikator_penjr {
  kode_verifikator_penjr serial [pk, note: "kode verifikator penjaringan"]
  kode_penjaringan int
  user_verif varchar(80) [note: "email user verifikator"]
  nama_verif varchar(100) [note: "nama verifikator"]

  note: "verifikator yang dapat surat tugas untuk memverifikasi vendor di penjaringan"
}

Table trx_undangan_penjr {
  kode_und_penjr serial [pk, note: "kode undangan penjaringan"]
  kode_penjaringan int4
  nama varchar
  email varchar
  alamat varchar
  nama_pic varchar
  no_hp_wa varchar
  tgl_awal timestamptz
  tgl_akhir timestamptz
  token varchar

  note: "Data vendor yg diundang langsung oleh PPK (metode penjaringan: 'undangan')"
}

Table trx_vendor_penjr {
  kode_vendor_penjr serial [pk]
  kode_penjaringan int4
  kode_vendor int4
  status_verifikasi status_verifikasi [note: "belum_diproses, proses_verifikasi, perbaikan_data, proses_evaluasi, diterima, ditolak"]
  alasan_ditolak text [note: "Alasan hasil evaluasi ditolak"]
  batas_waktu_perbaikan timestamptz
  file_daftar_kehadiran varchar(100)
  file_lainya varchar(100)
  file_ba_verif varchar(100)

  status_dpt status_dpt [note: "belum_ditetapkan, belum_penetapan, terpilih, tidak_terpilih"]
  alasan_tidak_terpilih text [note: "Alasan tidak terpilih sebagai DPT"]

  note: 'mencatat vendor yang memilih paket'
}

Table trx_undangan_verif {
  kode_undangan_verif serial [pk]
  kode_vendor_penjr int4
  tgl_undangan timestamptz
  is_online bool
  platform_konferensi varchar(100)
  link_konferensi text
  is_lokasi_dialamat_penyedia bool
  lokasi varchar(255)

  note: "Untuk mencatat jadwal verifikasi penyedia dengan DMAU"
}

Table trx_tim_teknis_pendukung {
  kode_tim_teknis_pendukung serial [pk]
  kode_undangan_verif int4
  email varchar(80)
  nama varchar(150)
}

Table trx_kehadiran_verif {
  kode_kehadiran serial [pk]
  kode_undangan_verif int4
  nama varchar(150)
  jabatan varchar(150)
}


Table ref_kab_kota {
  kode_kab_kota varchar(5) [pk]
  kode_provinsi varchar(5)
  kab_kota varchar
}

Table ref_jenis_vendor {
  kode_jenis_vendor int2 [pk]
  jenis_vendor varchar

  note: "Badan Usaha, Perorangan"
}

Table ref_kualifikasi_usaha {
  kode_kualifikasi_usaha int2 [pk]
  kualifikasi_usaha varchar(10)

  note: "Kecil, Menengah, Besar"
}

Table ref_vendor_register {
  kode_register serial [pk]
  kode_jenis_vendor int2
  nama_perusahaan varchar(100)
  email varchar(80)
  password varchar(100)
  no_telp varchar(30) [note: 'No Handphone whatsapp aktif kalau perorangan/ No. Telp kantor kalau badan usaha']
  nama_narahubung varchar(255)
  no_wa_narahubung varchar(20)
  swafoto varchar(100)
  status_register status_persetujuan [note: "status akun yang baru daftar (belum_diproses, proses, terima, tolak)"]
  alasan_ditolak text
  user_verif varchar(80) [note: "Email user yang memverifikasi"]
  udcr timestamptz
  udch timestamptz
  message varchar(255)
  similarity varchar(255)
  distance_percentage decimal
  distance_point decimal
  keypass varchar(255)
  kode_vendor int4 [ref: - ref_vendor.kode_vendor]

  note: "Vendor yang baru register ditampung disini dulu untuk diverifikasi"
}

Table ref_vendor_reg_history {
  kode_register serial [pk]
  kode_jenis_vendor int2
  nama_perusahaan varchar(100)
  email varchar(80)
  password varchar(100)
  no_telp varchar(30) [note: 'No Handphone whatsapp aktif kalau perorangan/ No. Telp kantor kalau badan usaha']
  nama_narahubung varchar(255)
  no_wa_narahubung varchar(20)
  swafoto varchar(100)
  status_register status_persetujuan [note: "status akun yang baru daftar (belum_diproses, proses, terima, tolak)"]
  alasan_ditolak text
  user_verif varchar(80) [note: "Email user yang memverifikasi"]
  udcr timestamptz
  udch timestamptz
  message varchar(255)
  similarity varchar(255)
  distance_percentage decimal
  distance_point decimal
  keypass varchar(255)
  kode_vendor int4 [ref: - ref_vendor.kode_vendor]

  note: "Vendor yang sudah diverifikasi (diterima/ditolak) dicatat kesini"
}

Enum status_form_dpt {
  proses
  ajukan_perubahan
  selesai
}

Table ref_vendor {
  kode_vendor serial [pk]
  kode_jenis_vendor int2
  nama_perusahaan varchar(100)
  is_tetap bool [default: false]
  status_form_luar_dpt status_form_dpt [note: "proses, ajukan_perubahan, selesai - Sebagai flag apakah vendor telah selesai mengisi form persyaratan"]
  udcr timestamptz
  udch timestamptz

  note: "Vendor adalah Penyedia - Vendor yang lolos verifikasi registrasi, disimpan disini"
}

Table ref_penanggung_jwb {
  kode_penanggung_jwb serial [pk]
  kode_vendor int4
  nik varchar(20)
  nama varchar(100)
  email varchar(80)
  jabatan varchar(100)
  file_s_kuasa text [note: "Surat Kuasa"]
  encrypt_key_s_kuasa varchar(255)
  is_aktif bool

  note: "Yang boleh TTE dari vendor"
}

Table ref_pakta_integritas {
  kode_pakta_integritas serial [pk]
  kode_vendor int4
  is_setuju bool
}

Table ref_datadiri_umum {
  kode_datadiri_umum serial [pk]
  kode_vendor int4
  nama varchar(150) [note: "Nama penyedia perorangan"]
  nama_badan_usaha varchar(150)
  nama_narahubung varchar(255) [note: 'Contact Person']
  kode_kualifikasi_usaha int2
  nomor_telp varchar(255) [note: 'Nomor telepon kantor atau rumah']
  no_handphone varchar(20) [note: 'Nomor HP Whatsapp']
  email varchar(80)
  kode_kab_kota_ktp varchar(5)
  alamat_ktp text
  kode_kab_kota_domisili varchar(5)
  alamat_domisili text
  is_alamat_sama bool [note: "Apakah alamat KTP dg Domisili sama ?"]
  file_skt text [note: "Surat Keterangan Domisili"]
  is_skt_selamanya bool [note:'Apakah Surat Keterangan Domisili berlaku selamanya?']
  skt_berlaku_awal date [default: null]
  skt_berlaku_akhir date [default: null]
  alamat_badan_usaha text

  custom jsonb

  note: "Untuk menyimpan 'Data Diri / Umum' Perorangan dan Badan Usaha"
}

Table ref_administrasi_pero {
  kode_adm serial [pk]
  kode_vendor int4

  file_skd text [note: "Surat Kebenaran Data"]
  is_skd_selamanya bool [note:'Apakah Surat Kebenaran Data berlaku selamanya?']
  skd_berlaku_awal date [default: null]
  skd_berlaku_akhir date [default: null]
  encrypt_key_skd varchar(255)

  custom_adm jsonb

  npwp varchar(20) [note: "Nomor NPWP"]
  file_npwp text
  is_npwp_selamanya bool [note:'Apakah berlaku selamanya?']
  npwp_berlaku_awal date [default: null]
  npwp_berlaku_akhir date [default: null]
  encrypt_key_npwp varchar(255)

  file_bukti_spt text
  is_bukti_spt_selamanya bool [note:'Apakah Bukti SPT berlaku selamanya?']
  bukti_spt_berlaku_awal date [default: null]
  bukti_spt_berlaku_akhir date [default: null]
  encrypt_key_bukti_spt varchar(255)

  file_skb_pph23 text [note: "Surat Keterangan Bebas PPh 23"]
  is_skb_pph23_selamanya bool [note:'Apakah selamanya?']
  skb_pph23_berlaku_awal date [default: null]
  skb_pph23_berlaku_akhir date [default: null]
  encrypt_key_skb_pph23 varchar(255)

  file_sk_pp23 text [note: "Surat Keterangan PP 23"]
  is_sk_pp23_selamanya bool [note:'Apakah berlaku selamanya?']
  sk_pp23_berlaku_awal date [default: null]
  sk_pp23_berlaku_akhir date [default: null]
  encrypt_key_sk_pp23 varchar(255)

  custom_npwp jsonb
}

Table ref_verif_administrasi_pero {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_adm int4

  is_file_skd_sesuai bool
  komentar_file_skd varchar(255)
  custom_adm jsonb

  is_npwp_sesuai bool
  komentar_npwp varchar(255)
  is_file_npwp_sesuai text
  komentar_file_npwp varchar(255)
  is_bukti_spt_sesuai text
  komentar_bukti_spt varchar(255)
  is_file_skb_pph23_sesuai text
  komentar_file_skb_pph23 varchar(255)
  is_file_sk_pp23_sesuai text
  komentar_file_sk_pp23 varchar(255)
  custom_npwp jsonb
}

Table trx_nilai_akhir {
  kode_penilaian serial [pk]
  kode_vendor_penjr int4

  komen_administrasi varchar(255)
  is_administrasi_lolos bool

  komen_teknis varchar(255)
  nilai_teknis int4

  komen_personalia varchar(255)
  nilai_personalia int4

  komen_kantor varchar(255)
  nilai_kantor int4

  komen_peralatan varchar(255)
  nilai_peralatan int4

  komen_pengalaman varchar(255)
  nilai_pengalaman int4

  nilai_sertifikat int4

  komen_keuangan varchar(255)
  is_keuangan_lolos bool [note: "Untuk peorangan, nilai akhir keuangan adalah lolos atau tidak lolos"]
  nilai_lap_keu int4 [note: "Untuk badan usaha, nilai akhir keuangan dinilai dengan angka"]

  nilai_total int4

  note: "hasil akhir penilaian perorangan & badan usaha di simpan disini"
}

Table ref_persentase_penilaian_tpl {
  kode_tpl int4 [pk]
  kode_jenis_vendor int4
  teknis int4
  personalia  int4
  kantor  int4
  peralatan  int4
  pengalaman  int4
  keuangan  int4
  lap_keu  int4
  sertifikat  int4
}

Table ref_persentase_penilaian {
  kode_persentase serial [pk]
  kode_penjaringan int4
  teknis int4
  personalia  int4
  kantor  int4
  peralatan  int4
  pengalaman  int4
  keuangan  int4
  lap_keu  int4
  sertifikat  int4
}

Table ref_ambang_batas_penilaian {
  kode_ambang_batas serial [pk]
  kode_penjaringan int4
  ambang_batas int4
}


Table ref_verif_datadiri_umum {
  kode_verif serial [pk]
  kode_datadiri_umum int4
  is_nama_sesuai bool
  komentar_nama varchar(255)
  is_nama_badan_usaha_sesuai bool
  komentar_nama_badan_usaha varchar(255)
  is_nama_narahubung_sesuai bool
  komentar_nama_narahubung varchar(255)
  is_kode_kualifikasi_usaha_sesuai bool
  komentar_kode_kualifikasi_usaha varchar(255)
  is_nomor_telp_sesuai bool
  komentar_nomor_telp varchar(255)
  is_nomor_handphone_sesuai bool
  komentar_nomor_handphone varchar(255)
  is_email_sesuai bool
  komentar_email varchar(255)
  is_kode_kab_kota_ktp_sesuai bool
  komentar_kode_kab_kota_ktp varchar(255)
  is_alamat_ktp_sesuai bool
  komentar_alamat_ktp varchar(255)
  is_kode_kab_kota_domisili_sesuai bool
  komentar_kode_kab_kota_domisili varchar(255)
  is_alamat_domisili_sesuai bool
  komentar_alamat_domisili varchar(255)
  is_is_alamat_sama_sesuai bool
  komentar_is_alamat_sama varchar(255)
  is_file_skt_sesuai bool
  komentar_file_skt varchar(255)
  is_alamat_badan_usaha_sesuai bool
  komentar_alamat_badan_usaha varchar(255)
  custom jsonb
}

Table ref_personalia_pero {
  kode_personalia serial [pk]
  kode_vendor int4
  nama varchar(100)
  nik varchar(20)
  tempat_lahir varchar(100)
  tgl_lahir date
  bidang_keahlian varchar(100)
  kode_jenjang_pendidikan int4
  program_studi varchar(100)

  file_ktp text
  is_ktp_selamanya bool [note:"Apakah KTP berlaku selamanya?"]
  ktp_berlaku_awal date [default: null]
  ktp_berlaku_akhir date [default: null]
  encrypt_key_ktp varchar(255)

  file_ijazah text
  is_ijazah_selamanya bool [note:"Apakah Ijazah berlaku selamanya?"]
  ijazah_berlaku_awal date [default: null]
  ijazah_berlaku_akhir date [default: null]
  encrypt_key_ijazah varchar(255)

  file_cv text
  is_cv_selamanya bool [note:"Apakah CV berlaku selamanya?"]
  cv_berlaku_awal date [default: null]
  cv_berlaku_akhir date [default: null]
  encrypt_key_cv varchar(255)

  custom_teknis jsonb

  note: "Teknis (Perorangan)"
}

table ref_pengalaman_pero {
  kode_pengalaman serial [pk]
  kode_vendor int4
  nama_pekerjaan varchar(100)
  posisi varchar(50)
  tgl_awal_pekerjaan date [default: null]
  tgl_akhir_pekerjaan date [default: null]
  nilai_pekerjaan int8
  file_bukti varchar(100)
  encrypt_key varchar
  custom jsonb
}

Table ref_sertif_pero {
  kode_sertif serial [pk]
  kode_vendor int4
  nm_sertifikat varchar(100)
  file_bukti varchar(100)
  encrypt_key varchar
  custom jsonb
}

Table ref_verif_personalia_pero {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_personalia int4

  is_nama_sesuai bool
  komentar_nama varchar(255)
  is_nik_sesuai bool
  komentar_nik varchar(255)
  is_tempat_lahir_sesuai bool
  komentar_tempat_lahir varchar(255)
  is_tgl_lahir_sesuai bool
  komentar_tgl_lahir varchar(255)
  is_bidang_keahlian_sesuai bool
  komentar_bidang_keahlian varchar(255)
  is_program_studi_sesuai bool
  komentar_program_studi varchar(255)
  is_file_ktp_sesuai bool
  komentar_file_ktp varchar(255)
  is_file_ijazah_sesuai bool
  komentar_file_ijazah varchar(255)
  is_file_cv_sesuai bool
  komentar_file_cv varchar(255)

  custom_teknis jsonb
}

Table ref_verif_pengalaman_pero {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_pengalaman int4

  is_nama_pekerjaan_sesuai bool
  komentar_nama_pekerjaan varchar(255)
  is_posisi_sesuai bool
  komentar_posisi varchar(255)
  is_jangka_waktu_sesuai bool
  komentar_jangka_waktu varchar(255)
  is_nilai_pekerjaan_sesuai bool
  komentar_nilai_pekerjaan varchar(255)
  is_file_bukti_sesuai bool
  komentar_file_bukti varchar(255)

  custom jsonb

  nilai int4
}

Table ref_verif_sertif_pero {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_sertif int4

  is_nm_sertifikat_sesuai bool
  komentar_nm_sertifikat varchar(255)
  is_file_bukti_sesuai bool
  komentar_file_bukti varchar(255)

  custom jsonb

  nilai int4
}

Table ref_keuangan_pero {
  kode_keuangan serial [pk]
  kode_vendor int4
  nm_pemilik_rek varchar(100)
  no_rek varchar(50)
  sandi_bank varchar(4)

  file_buku_rek text
  is_buku_rek_selamanya bool [note:"Apakah Buku Rekening berlaku selamanya?"]
  buku_rek_berlaku_awal date [default: null]
  buku_rek_berlaku_akhir date [default: null]
  encrypt_key_buku_rek varchar(255)

  custom jsonb

  note: "Data Keuangan Perorangan"
}


Table ref_keuangan_bu {
  kode_keuangan serial [pk]
  kode_vendor int4
  nm_pemilik_rek varchar(100)
  no_rek varchar(50)
  sandi_bank varchar(4)

  file_buku_rek text
  is_buku_rek_selamanya bool [note:"Apakah Buku Rekening berlaku selamanya?"]
  buku_rek_berlaku_awal date [default: null]
  buku_rek_berlaku_akhir date [default: null]
  encrypt_key_buku_rek varchar(255)

  custom_bank jsonb

  file_lap_keu text
  is_lap_keu_selamanya bool
  lap_keu_berlaku_awal date [default: null]
  lap_keu_berlaku_akhir date [default: null]
  encrypt_key_lap_keu varchar(255)

  file_lap_keu_audited text
  is_lap_keu_audited_selamanya bool
  lap_keu_audited_berlaku_awal date [default: null]
  lap_keu_audited_berlaku_akhir date [default: null]
  encrypt_key_lap_keu_audited varchar(255)

  custom_lap_keu jsonb

  note: "Data Keuangan Badan Usaha"
}

Table ref_verif_keuangan_bu {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_keuangan int4

  is_nm_pemilik_rek_sesuai bool
  komentar_nm_pemilik_rek varchar(255)
  is_no_rek_sesuai bool
  komentar_no_rek varchar(255)
  is_sandi_bank_sesuai bool
  komentar_sandi_bank varchar(255)
  is_file_buku_rek_sesuai bool
  komentar_file_buku_rek varchar(255)

  custom_bank jsonb

  is_file_lap_keu_sesuai bool
  komentar_file_lap_keu varchar(255)
  is_file_lap_keu_audited_sesuai bool
  komentar_file_lap_keu_audited varchar(255)

  custom_lap_keu jsonb
}



Table ref_verif_keuangan_pero {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_keuangan int4

  is_nm_pemilik_rek_sesuai bool
  komentar_nm_pemilik_rek varchar(255)
  is_no_rek_sesuai bool
  komentar_no_rek varchar(255)
  is_sandi_bank_sesuai bool
  komentar_sandi_bank varchar(255)
  is_file_buku_rek_sesuai bool
  komentar_file_buku_rek varchar(255)

  custom jsonb
}



Table ref_adm_bu {
  kode_adm_bu serial [pk]
  kode_vendor int4
  file_fis text [note: "Form Ikut Serta"]
  is_fis_selamanya bool [note:"Apakah Form Ikut Serta berlaku selamanya?"]
  fis_berlaku_awal date [default: null]
  fis_berlaku_akhir date [default: null]
  encrypt_key_fis varchar(255)

  file_s_kuasa text [note: "Surat Kuasa"]
  is_s_kuasa_selamanya bool [note:"Apakah Surat Kuasa berlaku selamanya?"]
  s_kuasa_berlaku_awal date [default: null]
  s_kuasa_berlaku_akhir date [default: null]
  encrypt_key_s_kuasa varchar(255)

  file_spkd text [note: "Surat Pernyataan Kebenaran Data"]
  is_spkd_selamanya bool [note:"Apakah Surat Pernyataan Kebenaran Data berlaku selamanya?"]
  spkd_berlaku_awal date [default: null]
  spkd_berlaku_akhir date [default: null]
  encrypt_key_spkd varchar(255)

  custom jsonb

  note: "Administrasi (Badan Usaha)"
}

Table ref_verif_adm_bu {
  kode_verif serial [pk]

  kode_vendor_penjr int4
  kode_adm_bu int4

  is_file_fis_sesuai bool
  komentar_file_fis varchar(255)
  is_file_s_kuasa_sesuai bool
  komentar_file_s_kuasa varchar(255)
  is_file_spkd_sesuai bool
  komentar_file_spkd varchar(255)

  custom jsonb
}

Table ref_lan_hukum_bu {
  kode_lan_hukum serial [pk]
  kode_vendor int4
  no_akta_awal varchar(255)
  tgl_akta_awal date
  notaris_awal varchar(100)
  no_sah_awal varchar(255) [note: "Nomor Pengesahan / Pendaftaran"]
  file_akta_awal text [note: "Scan Akta Pendirian Awal"]
  is_akta_awal_selamanya bool [note:"Apakah Akta Awal berlaku selamanya?"]
  akta_awal_berlaku_awal date [default: null]
  akta_awal_berlaku_akhir date [default: null]
  encrypt_key_akta_awal varchar(255)

  no_akta_rubah varchar(255) [note: "No. Akta setelah Perubahan Terakhir Akta Pendirian Badan Usaha /Anggaran Dasar Koperasi"]
  tgl_akta_rubah date
  notaris_rubah varchar(100)
  no_sah_rubah varchar(255) [note: "Nomor Pengesahan / Pendaftaran"]
  file_akta_rubah text [note: "Scan Akta Pendirian Terakhir"]
  is_akta_rubah_selamanya bool [note:"Apakah Akta Terakhir berlaku selamanya?"]
  akta_rubah_berlaku_awal date [default: null]
  akta_rubah_berlaku_akhir date [default: null]
  encrypt_key_akta_rubah varchar(255)

  custom jsonb

  note: "Landasan Hukum Pendirian Badan Usaha"
}

Table ref_verif_lan_hukum_bu {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_lan_hukum int4

  is_no_akta_awal_sesuai bool
  komentar_no_akta_awal varchar(255)
  is_tgl_akta_awal_sesuai bool
  komentar_tgl_akta_awal varchar(255)
  is_notaris_awal_sesuai bool
  komentar_notaris_awal varchar(255)
  is_no_sah_awal_sesuai bool
  komentar_no_sah_awal varchar(255)
  is_file_akta_awal_sesuai bool
  komentar_file_akta_awal varchar(255)
  is_no_akta_rubah_sesuai bool
  komentar_no_akta_rubah varchar(255)
  is_tgl_akta_rubah_sesuai bool
  komentar_tgl_akta_rubah varchar(255)
  is_notaris_rubah_sesuai bool
  komentar_notaris_rubah varchar(255)
  is_no_sah_rubah_sesuai bool
  komentar_no_sah_rubah varchar(255)
  is_file_akta_rubah_sesuai bool
  komentar_file_akta_rubah varchar(255)

  custom jsonb
}


Table ref_komisaris_bu {
  kode_komisaris serial [pk]
  kode_vendor int4
  nm_komisaris varchar(100)
  jbtn_komisaris varchar(100)
  hp_komisaris varchar(35)
  no_ktp_komisaris varchar(30)
  path_ktp_komisaris varchar(200)
  is_ktp_selamanya bool [note:'Apakah KTP berlaku selamanya?']
  ktp_berlaku_awal date [default: null]
  ktp_berlaku_akhir date [default: null]
  encrypt_key varchar(255)
  custom jsonb
}

Table ref_verif_komisaris {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_komisaris int4
  is_sesuai bool
  komentar varchar(255)
}

Enum bentuk_bu {
  pt
  cv
}

Table ref_pengurus_bu {
  kode_pengurus_bu serial [pk]
  kode_vendor int4
  bentuk_bu bentuk_bu [note: "Bentuk Badan Usaha"]
  custom jsonb

  note: "Pengurus badan usaha"
}

Table ref_verif_direksi {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_direksi int4
  is_sesuai bool
  komentar varchar(255)
}

Table ref_direksi_bu {
  kode_direksi serial [pk]
  kode_vendor int4
  nm_direksi varchar(100)
  jbtn_direksi varchar(100)
  hp_direksi varchar(35)
  no_ktp_direksi varchar(30)
  path_ktp_direksi varchar(200)
  is_ktp_selamanya bool [note:'Apakah KTP berlaku selamanya?']
  ktp_berlaku_awal date [default: null]
  ktp_berlaku_akhir date [default: null]
  encrypt_key varchar(255)
  custom jsonb
}


Table trx_pengurus_bu_verif {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_pengurus_bu int4
  is_bentuk_bu_sesuai bool
  komentar_bentuk_bu varchar(255)

  custom jsonb
}

Table ref_izin_usaha_bu {
  kode_izin_usaha serial [pk]
  kode_vendor int
  jenis_izin_usaha jenis_izin_usaha [note: "nib, sbu, lainya"]
  nama varchar(150)
  nomor_izin varchar(150)
  kode varchar [note: 'Kalau jenis izinnya NIB, masukan Kode KBLI / Kalau jenis izinnya SBU, masukan Kode SBU']
  judul varchar(150)
  file_izin varchar(170)
  is_izin_selamanya bool [note:'Apakah Izin berlaku selamanya?']
  izin_berlaku_awal date [default: null]
  izin_berlaku_akhir date [default: null]
  encrypt_key varchar(255)
  custom jsonb
}

Table ref_verif_izin_usaha_bu {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_izin_usaha int4
  is_sesuai bool
  komentar varchar(255)
}


Table ref_sertifikat_usaha_bu {
  kode_sertifikat_usaha serial [pk]
  kode_vendor int4
  nama_judul varchar(150)
  penerbit varchar(50)
  tanggal date
  file_sertif varchar(100)
  is_sertif_selamanya bool [note:'Apakah sertifikat berlaku selamanya?']
  sertif_berlaku_awal date [default: null]
  sertif_berlaku_akhir date [default: null]
  encrypt_key varchar(255)
  custom jsonb
}

Table ref_verif_sertifikat_usaha_bu {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_sertifikat_usaha int4
  is_sesuai bool
  komentar varchar(255)
}


Table ref_saham_bu {
  kode_saham serial [pk]
  kode_vendor int
  nm_saham varchar(100) [note: 'Nama pemegang saham']
  no_ktp_saham varchar(20)
  alamat_saham text
  persentase_saham varchar(50)
  path_saham varchar(100)
  is_saham_selamanya bool [note:'Apakah file berlaku selamanya?']
  saham_berlaku_awal date [default: null]
  saham_berlaku_akhir date [default: null]
  encrypt_key varchar(255)
  custom jsonb
}

Table ref_verif_saham_bu {
  kode_verif serial [pk]
  kode_vendor_penjr int4
  kode_saham int4
  is_sesuai bool
  komentar varchar(255)
}



Table ref_data_pajak_bu {
  kode_data_pajak serial [pk]
  kode_vendor int4

  npwp varchar(30) [note: "Nomor NPWP"]

  file_npwp text
  is_npwp_selamanya bool [note:'Apakah NPWP berlaku selamanya?']
  npwp_berlaku_awal date [default: null]
  npwp_berlaku_akhir date [default: null]
  encrypt_key_npwp varchar(255)

  file_bukti_kswp text [note: "Bukti KSWP"]
  is_bukti_kswp_selamanya bool [note:'Apakah berlaku selamanya?']
  bukti_kswp_berlaku_awal date [default: null]
  bukti_kswp_berlaku_akhir date [default: null]
  encrypt_key_bukti_kswp varchar(255)

  file_bukti_spt text [note: "Bukti Penyampaian SPT"]
  is_bukti_spt_selamanya bool [note:'Apakah berlaku selamanya?']
  bukti_spt_berlaku_awal date [default: null]
  bukti_spt_berlaku_akhir date [default: null]
  encrypt_key_bukti_spt varchar(255)

  file_skb_pph23 text [note: "Surat Keterangan Bebas PPh 23"]
  is_skb_pph23_selamanya bool [note:'Apakah berlaku selamanya?']
  skb_pph23_berlaku_awal date [default: null]
  skb_pph23_berlaku_akhir date [default: null]
  encrypt_key_skb_pph23 varchar(255)

  file_sk_pp23 text [note: "Surat Keterangan PP 23"]
  is_sk_pp23_selamanya bool [note:'Apakah berlaku selamanya?']
  sk_pp23_berlaku_awal date [default: null]
  sk_pp23_berlaku_akhir date [default: null]
  encrypt_key_sk_pp23 varchar(255)

  custom jsonb

  note: "Data Pajak (Badan Usaha)"
}

Table ref_verif_data_pajak_bu {
  kode_verif serial [pk]
  kode_data_pajak int4
  kode_vendor_penjr int4

  npwp varchar(20) [note: "Nomor NPWP"]
  is_npwp_sesuai bool
  komentar_npwp varchar(255)

  file_npwp text
  is_file_npwp_sesuai bool
  komentar_file_npwp varchar(255)

  file_kswp text
  is_file_kswp_sesuai bool
  komentar_file_kswp varchar(255)

  file_bukti_spt text [note: "NPWP"]
  is_file_bukti_spt_sesuai bool
  komentar_file_bukti_spt varchar(255)

  file_skb_pph23 text [note: "NPWP"]
  is_file_skb_pph23_sesuai bool
  komentar_file_skb_pph23 varchar(255)

  file_sk_pp23 text [note: "NPWP"]
  is_file_sk_pp23_sesuai bool
  komentar_file_sk_pp23 varchar(255)

  custom jsonb
}

Table ref_jenjang_pendidikan {
  kode_jenjang_pendidikan int4 [pk]
  jenjang_pendidikan varchar(20)
}

Table ref_tenaga_ahli_bu {
  kode_tenaga_ahli serial [pk]
  kode_vendor int4
  nama varchar(100)
  no_ktp varchar(20)
  file_ktp varchar(100)
  is_ktp_selamanya bool [note:'Apakah KTP berlaku selamanya?']
  ktp_berlaku_awal date [default: null]
  ktp_berlaku_akhir date [default: null]
  encrypt_key_ktp varchar
  tempat_lahir varchar(50)
  tgl_lahir date
  posisi varchar(50)
  kode_jenjang_pendidikan int4
  program_studi varchar(50)
  file_ijazah varchar(100)
  is_ijazah_selamanya bool [note:'Apakah ijazah berlaku selamanya?']
  ijazah_berlaku_awal date [default: null]
  ijazah_berlaku_akhir date [default: null]
  encrypt_key_ijazah varchar
  file_cv varchar(100)
  is_cv_selamanya bool [note:'Apakah cv berlaku selamanya?']
  cv_berlaku_awal date [default: null]
  cv_berlaku_akhir date [default: null]
  encrypt_key_cv varchar
  custom jsonb
}

Table ref_tenaga_pendukung_bu {
  kode_tenaga_pendukung serial [pk]
  kode_vendor int4
  nama varchar(100)
  no_ktp varchar(20)
  file_ktp varchar(100)
  is_ktp_selamanya bool [note:'Apakah KTP berlaku selamanya?']
  ktp_berlaku_awal date [default: null]
  ktp_berlaku_akhir date [default: null]
  encrypt_key_ktp varchar
  tempat_lahir varchar(50)
  tgl_lahir date
  posisi varchar(50)
  kode_jenjang_pendidikan int4
  program_studi varchar(50)
  file_ijazah varchar(100)
  is_ijazah_selamanya bool [note:'Apakah ijazah berlaku selamanya?']
  ijazah_berlaku_awal date [default: null]
  ijazah_berlaku_akhir date [default: null]
  encrypt_key_ijazah varchar
  file_cv varchar(100)
  is_cv_selamanya bool [note:'Apakah cv berlaku selamanya?']
  cv_berlaku_awal date [default: null]
  cv_berlaku_akhir date [default: null]
  encrypt_key_cv varchar
  custom jsonb
}

Table ref_pengalaman_ta {
  kode_pengalaman_ta serial [pk]
  kode_tenaga_ahli int4
  pengalaman varchar(255)
  file_bukti varchar(100)
  encrypt_key varchar

  note: 'Daftar pengalaman tenaga ahli badan usaha'
}

Table ref_sertif_ta {
  kode_sertif_ta serial [pk]
  kode_tenaga_ahli int4
  sertifikat varchar(255)
  file_bukti varchar(100)
  encrypt_key varchar

  note: 'Daftar sertifikat tenaga ahli badan usaha'
}

Table ref_pengalaman_tp {
  kode_pengalaman_tp serial [pk]
  kode_tenaga_pendukung int4
  pengalaman varchar(255)
  file_bukti varchar(100)
  encrypt_key varchar

  note: 'Daftar pengalaman tenaga pendukung badan usaha'
}

Table ref_sertif_tp {
  kode_sertif_tp serial [pk]
  kode_tenaga_pendukung int4
  sertifikat varchar(255)
  file_bukti varchar(100)
  encrypt_key varchar

  note: 'Daftar sertifikat tenaga pendukung badan usaha'
}

Table ref_verif_tenaga_ahli_bu {
  kode_verif serial [pk]
  kode_tenaga_ahli int4
  kode_vendor_penjr int4

  is_sesuai bool
  komentar varchar(255)
  nilai int4
}

Table ref_verif_tenaga_pendukung_bu {
  kode_verif serial [pk]
  kode_tenaga_pendukung int4
  kode_vendor_penjr int4

  is_sesuai bool
  komentar varchar(255)
  nilai int4
}

Table ref_kepemilikan {
  kode_kepemilikan int4 [pk]
  kepemilikan varchar(20)
}

Table ref_kondisi {
  kode_kondisi int2 [pk]
  kondisi varchar(20)
}

Table ref_kantor_bu {
  kode_kantor serial [pk]
  kode_vendor int
  nama varchar(30)
  alamat text

  kode_kondisi int4
  kode_kepemilikan int4

  file_bukti varchar(100) [note: "Bukti kepemilikan"]
  is_bukti_selamanya bool [note:'Apakah berlaku selamanya?']
  bukti_berlaku_awal date [default: null]
  bukti_berlaku_akhir date [default: null]
  encrypt_key_bukti varchar(255)

  file_foto varchar(100)
  is_foto_selamanya bool [note:'Apakah foto berlaku selamanya?']
  foto_berlaku_awal date [default: null]
  foto_berlaku_akhir date [default: null]
  encrypt_key_foto varchar(255)

  custom jsonb
}

Table ref_verif_kantor_bu {
  kode_verif serial [pk]
  kode_kantor int4
  kode_vendor_penjr int4

  is_sesuai bool
  komentar varchar(255)
  nilai int4
}

Table ref_fasilitas_bu {
  kode_fasilitas serial [pk]
  kode_vendor int
  nama varchar(100)
  jumlah varchar(130)
  kode_kondisi int4
  kode_kepemilikan int4

  file_kepemilikan varchar(100)
  is_kepemilikan_selamanya bool [note:'Apakah kepemilikan berlaku selamanya?']
  kepemilikan_berlaku_awal date [default: null]
  kepemilikan_berlaku_akhir date [default: null]
  encrypt_key_kepemilikan varchar(255)

  file_foto varchar(100)
  is_foto_selamanya bool [note:'Apakah foto berlaku selamanya?']
  foto_berlaku_awal date [default: null]
  foto_berlaku_akhir date [default: null]
  encrypt_key_foto varchar(255)
  custom jsonb
}

Table ref_verif_fasilitas_bu {
  kode_verif serial [pk]
  kode_fasilitas int4
  kode_vendor_penjr int4

  is_sesuai bool
  komentar varchar(255)
  nilai int4
}


Table ref_pengalaman_bu {
  kode_pengalaman_bu serial [pk]
  kode_vendor int
  nama_pekerjaan text
  tahun_pekerjaan int4
  pemberi_kerja varchar(160)
  nilai_pekerjaan int8
  tgl_awal_pekerjaan date [default: null]
  tgl_akhir_pekerjaan date [default: null]
  no_kontrak varchar(50)

  file_kontrak varchar(100)
  is_kontrak_selamanya bool [note:'Apakah kontrak berlaku selamanya?']
  kontrak_berlaku_awal date [default: null]
  kontrak_berlaku_akhir date [default: null]
  encrypt_key_kontrak varchar(255)

  file_bast varchar(100)
  is_bast_selamanya bool [note:'Apakah bast berlaku selamanya?']
  bast_berlaku_awal date [default: null]
  bast_berlaku_akhir date [default: null]
  encrypt_key_bast varchar(255)

  custom jsonb
}

Table ref_verif_pengalaman_bu {
  kode_verif serial [pk]
  kode_pengalaman_bu int4
  kode_vendor_penjr int4

  is_sesuai bool
  komentar varchar(255)
  nilai int4

  // Gak Perlu ada field custom karena diverifikasinya per row
}


/*
Table ref_custom_item {
  kode_ci serial [pk]
  nama_tabel varchar(80)
  kode_penjaringan int4
  ci_list jsonb
}
*/

Table ref_tipe_input {
  tipe_input varchar(80) [pk]
  regex_validation varchar
}


// ---------------------------------
// Pengeluaran Penyedia dari DPT
// ---------------------------------
Table ref_v_keluar_dpt {
  kode_v_keluar_dpt serial [pk]
  tgl_pengajuan timestamptz
  kode_vendor int4
  kode_vendor_penjr int4
  kode_sanksi_vendor int2
  teks_alasan text
  file_bukti_dukung text
  kode_status_keluar_dpt int2
  alasan_tolak_usulan text
  file_bukti_dukung_sanggahan text
  alasan_sanggahan text
  file_dokumen text
  file_surat_keputusan text
}

Table ref_sanksi_vendor {
  kode_sanksi_vendor int2 [pk]
  nama_sanksi varchar(100)
}

Table ref_status_keluar_dpt {
  kode_status_keluar_dpt serial [pk]
  status varchar(100)
}

Table trx_undangan_pemeriksaan_keluar_dpt {
  kode_undangan serial [pk]
  is_online bool
  platform_konferensi_video varchar(100)
  link_konferensi_video varchar(255)
  lokasi varchar(100)
  file_surat_ke_ppk varchar(100)
  is_terlaksana bool
}



Ref: "ref_kualifikasi_usaha"."kode_kualifikasi_usaha" < "ref_datadiri_umum"."kode_kualifikasi_usaha"

Ref: "ref_jenis_vendor"."kode_jenis_vendor" < "ref_vendor"."kode_jenis_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_datadiri_umum"."kode_vendor"

Ref: "ref_kab_kota"."kode_kab_kota" < "ref_datadiri_umum"."kode_kab_kota_ktp"

Ref: "ref_kab_kota"."kode_kab_kota" < "ref_datadiri_umum"."kode_kab_kota_domisili"

Ref: "ref_vendor"."kode_vendor" < "ref_komisaris_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "trx_vendor_penjr"."kode_vendor"


Ref: "trx_penjaringan"."kode_penjaringan" < "trx_vendor_penjr"."kode_penjaringan"

Ref: "ref_vendor"."kode_vendor" < "ref_direksi_bu"."kode_vendor"

Ref: "ref_komisaris_bu"."kode_komisaris" < "ref_verif_komisaris"."kode_komisaris"

Ref: "ref_direksi_bu"."kode_direksi" < "ref_verif_direksi"."kode_direksi"

Ref: "ref_pengurus_bu"."kode_pengurus_bu" < "trx_pengurus_bu_verif"."kode_pengurus_bu"


Ref: "ref_vendor"."kode_vendor" < "ref_pakta_integritas"."kode_vendor"

Ref: "ref_jenis_pengadaan"."kode_jenis_pengadaan" < "trx_penjaringan"."kode_jenis_pengadaan"


Ref: "trx_kategori"."kode_trx_kategori" < "trx_penjaringan"."kode_trx_kategori"







Ref: "ref_vendor"."kode_vendor" < "ref_pengurus_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_izin_usaha_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_saham_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_data_pajak_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_tenaga_ahli_bu"."kode_vendor"

Ref: "ref_tenaga_ahli_bu"."kode_tenaga_ahli" < "ref_pengalaman_ta"."kode_tenaga_ahli"

Ref: "ref_jenjang_pendidikan"."kode_jenjang_pendidikan" < "ref_tenaga_ahli_bu"."kode_jenjang_pendidikan"

Ref: "ref_tenaga_ahli_bu"."kode_tenaga_ahli" < "ref_sertif_ta"."kode_tenaga_ahli"

Ref: "ref_tenaga_pendukung_bu"."kode_tenaga_pendukung" < "ref_pengalaman_tp"."kode_tenaga_pendukung"

Ref: "ref_tenaga_pendukung_bu"."kode_tenaga_pendukung" < "ref_sertif_tp"."kode_tenaga_pendukung"

Ref: "ref_vendor"."kode_vendor" < "ref_tenaga_pendukung_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_kantor_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_fasilitas_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_pengalaman_bu"."kode_vendor"

Ref: "trx_penjaringan"."kode_penjaringan" < "trx_verifikator_penjr"."kode_penjaringan"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "trx_undangan_verif"."kode_vendor_penjr"

Ref: "trx_penjaringan"."kode_penjaringan" < "trx_undangan_penjr"."kode_penjaringan"

Ref: "trx_undangan_verif"."kode_undangan_verif" < "trx_tim_teknis_pendukung"."kode_undangan_verif"


Ref: "ref_vendor"."kode_vendor" < "ref_administrasi_pero"."kode_vendor"





Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_administrasi_pero"."kode_vendor_penjr"

Ref: "ref_datadiri_umum"."kode_datadiri_umum" < "ref_verif_datadiri_umum"."kode_datadiri_umum"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_pengalaman_pero"."kode_vendor_penjr"

Ref: "ref_pengalaman_pero"."kode_pengalaman" < "ref_verif_pengalaman_pero"."kode_pengalaman"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_sertif_pero"."kode_vendor_penjr"

Ref: "ref_sertif_pero"."kode_sertif" < "ref_verif_sertif_pero"."kode_sertif"

Ref: "ref_sanksi_vendor"."kode_sanksi_vendor" < "ref_v_keluar_dpt"."kode_sanksi_vendor"

Ref: "ref_status_keluar_dpt"."kode_status_keluar_dpt" < "ref_v_keluar_dpt"."kode_status_keluar_dpt"


Ref: "ref_vendor"."kode_vendor" < "ref_v_keluar_dpt"."kode_vendor"

Ref: "ref_kat_persyaratan"."kode_kat_persyaratan" < "ref_subkat_persyaratan"."kode_kat_persyaratan"

Ref: "ref_subkat_persyaratan"."kode_subkat" < "ref_kat_item_tanya"."kode_subkat"

Ref: "ref_kat_item_tanya"."kode_kat_item_tanya" < "ref_item_tanya"."kode_kat_item_tanya"

Ref: "ref_subkat_persyaratan"."kode_subkat" < "trx_ketentuan_umum_khusus"."kode_subkat"


Ref: "ref_vendor"."kode_vendor" < "ref_keuangan_pero"."kode_vendor"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_keuangan_pero"."kode_vendor_penjr"

Ref: "ref_keuangan_pero"."kode_keuangan" < "ref_verif_keuangan_pero"."kode_keuangan"

Ref: "ref_adm_bu"."kode_adm_bu" < "ref_verif_adm_bu"."kode_adm_bu"


Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_adm_bu"."kode_vendor_penjr"

Ref: "ref_lan_hukum_bu"."kode_lan_hukum" < "ref_verif_lan_hukum_bu"."kode_lan_hukum"


Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_lan_hukum_bu"."kode_vendor_penjr"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "trx_pengurus_bu_verif"."kode_vendor_penjr"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_komisaris"."kode_vendor_penjr"
Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_direksi"."kode_vendor_penjr"


Ref: "ref_izin_usaha_bu"."kode_izin_usaha" < "ref_verif_izin_usaha_bu"."kode_izin_usaha"

Ref: "ref_sertifikat_usaha_bu"."kode_sertifikat_usaha" < "ref_verif_sertifikat_usaha_bu"."kode_sertifikat_usaha"


Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_izin_usaha_bu"."kode_vendor_penjr"
Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_sertifikat_usaha_bu"."kode_vendor_penjr"



Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_saham_bu"."kode_vendor_penjr"
Ref: "ref_saham_bu"."kode_saham" < "ref_verif_saham_bu"."kode_saham"


Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_data_pajak_bu"."kode_vendor_penjr"


Ref: "ref_data_pajak_bu"."kode_data_pajak" < "ref_verif_data_pajak_bu"."kode_data_pajak"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_tenaga_ahli_bu"."kode_vendor_penjr"
Ref: "ref_tenaga_ahli_bu"."kode_tenaga_ahli" < "ref_verif_tenaga_ahli_bu"."kode_tenaga_ahli"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_tenaga_pendukung_bu"."kode_vendor_penjr"
Ref: "ref_tenaga_pendukung_bu"."kode_tenaga_pendukung" < "ref_verif_tenaga_pendukung_bu"."kode_tenaga_pendukung"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_kantor_bu"."kode_vendor_penjr"
Ref: "ref_kantor_bu"."kode_kantor" < "ref_verif_kantor_bu"."kode_kantor"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_fasilitas_bu"."kode_vendor_penjr"
Ref: "ref_fasilitas_bu"."kode_fasilitas" < "ref_verif_fasilitas_bu"."kode_fasilitas"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_pengalaman_bu"."kode_vendor_penjr"
Ref: "ref_pengalaman_bu"."kode_pengalaman_bu" < "ref_verif_pengalaman_bu"."kode_pengalaman_bu"


Ref: "ref_tipe_input"."tipe_input" < "ref_item_tanya"."tipe_input"
Ref: "ref_tipe_input"."tipe_input" < "ref_item_tanya_tpl"."tipe_input"

Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "ref_verif_keuangan_bu"."kode_vendor_penjr"
Ref: "ref_keuangan_bu"."kode_keuangan" < "ref_verif_keuangan_bu"."kode_keuangan"


Ref: "trx_vendor_penjr"."kode_vendor_penjr" < "trx_nilai_akhir"."kode_vendor_penjr"

Ref: "ref_vendor"."kode_vendor" < "ref_adm_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_lan_hukum_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_keuangan_bu"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_pengalaman_pero"."kode_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_sertif_pero"."kode_vendor"

Ref: "ref_kepemilikan"."kode_kepemilikan" < "ref_kantor_bu"."kode_kepemilikan"

Ref: "ref_kepemilikan"."kode_kepemilikan" < "ref_fasilitas_bu"."kode_kepemilikan"

Ref: "ref_jenis_vendor"."kode_jenis_vendor" < "trx_penjaringan"."kode_jenis_vendor"


Ref: "trx_penjaringan"."kode_penjaringan" < "trx_ketentuan_umum_khusus"."kode_penjaringan"

Ref: "ref_kondisi"."kode_kondisi" < "ref_kantor_bu"."kode_kondisi"

Ref: "ref_kualifikasi_usaha"."kode_kualifikasi_usaha" < "trx_penjaringan"."kode_kualifikasi_usaha"

Ref: "trx_penjaringan"."kode_penjaringan" < "ref_item_tanya"."kode_penjaringan"



Ref: "ref_kat_item_tanya"."kode_kat_item_tanya" < "ref_item_tanya_tpl"."kode_kat_item_tanya"

Ref: "trx_penjaringan"."kode_penjaringan" < "ref_persentase_penilaian"."kode_penjaringan"

Ref: "trx_penjaringan"."kode_penjaringan" < "ref_ambang_batas_penilaian"."kode_penjaringan"

Ref: "ref_jenis_vendor"."kode_jenis_vendor" < "ref_persentase_penilaian_tpl"."kode_jenis_vendor"

Ref: "ref_vendor"."kode_vendor" < "ref_penanggung_jwb"."kode_vendor"

Ref: "ref_jenjang_pendidikan"."kode_jenjang_pendidikan" < "ref_personalia_pero"."kode_jenjang_pendidikan"

Ref: "ref_status_pengajuan_penjr"."kode_status_pengajuan" < "trx_penjaringan"."kode_status_pengajuan"

Ref: "trx_undangan_verif"."kode_undangan_verif" < "trx_kehadiran_verif"."kode_undangan_verif"